"use client"

import type React from "react"

import { useState } from "react"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { BarChart3, TrendingUp, Globe, Clock, ArrowRight, Download, Eye, CheckCircle } from "lucide-react"
import { Info } from "lucide-react";
import { fetchFromAPI } from "@/lib/utils";


export default function DemoPage() {
  const [email, setEmail] = useState("")
  const [website, setWebsite] = useState("")
  const [isSubmitted, setIsSubmitted] = useState(false)

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    setIsSubmitted(true)
  }

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-indigo-50 via-white to-emerald-50 py-10">
        
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
           
              <Badge
                 className="mb-4 bg-indigo-100 text-indigo-700 hover:bg-indigo-200 text-xs px-3 py-1.5 font-medium rounded-full shadow-sm transition-all duration-200"> 

              🚀 Interactive Demo
            </Badge>
              <h1 className="text-3xl sm:text-3xl lg:text-4xl font-extrabold text-gray-900 mb-5 leading-tight">
              Experience AI-Powered SEO Reports</h1>

            <h2 className="text-2xl lg:text-3xl font-black bg-gradient-to-r from-indigo-600 to-purple-500 bg-clip-text text-transparent mb-5 leading-tight">
            Try a sample SEO report — see how Sumryze delivers insights, not just data.
            </h2>

              
            <p className="text-sm sm:text-sm lg:text-sm text-gray-700 mb-8 max-w-3xl mx-auto leading-relaxed">

              Explore a real SEO report generated by our AI-powered platform. See the insights and recommendations that
              help agencies deliver exceptional value to their clients.
            </p>


              {/* CTA Buttons */}

             <div className="flex flex-col sm:flex-row justify-center items-center gap-4 mt-8 px-4">

                {/* Primary Button */}
                <a
                 href="/demo#report"
                className="w-full sm:w-auto px-10 py-2 text-sm font-semibold text-white bg-indigo-600 hover:bg-indigo-700 rounded-lg shadow-md text-center transition duration-300"
                >
                Start Free Trial
               </a>

               {/* Secondary Button */}
               <a
               href="/features"
               className="w-full sm:w-auto px-8 py-2 text-sm font-semibold text-indigo-600 bg-white border border-indigo-300 hover:bg-gray-50 rounded-lg shadow-sm text-center transition duration-300"
              >
               Explore Features
             </a>

          </div>         
            
          </div>
        </div>
      </section>

     {/* Sample Report Section */}
<section id="sample-report" className="py-6 bg-white">
  <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
      {/* Report Preview */}
      <div>
        <h2 className="text-3xl font-bold text-gray-900 mb-4">Sample SEO Report</h2>
        <p className="text-sm text-gray-600 mb-6">
          This is a real report generated for a sample e-commerce website. Explore the different sections to see
          the depth of analysis and insights provided.
        </p>

        <Tabs defaultValue="overview" className="w-full">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="overview">Overview</TabsTrigger>
            <TabsTrigger value="technical">Technical</TabsTrigger>
            <TabsTrigger value="keywords">Keywords</TabsTrigger>
          </TabsList>

          <TabsContent value="overview" className="mt-6">
            <Card className="border-0 shadow-lg">
              <CardHeader>
                <CardTitle className="flex items-center">
                  <BarChart3 className="h-5 w-5 text-indigo-600 mr-2" />
                  Performance Overview
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 gap-4 mb-6">
                  <div className="bg-emerald-50 p-4 rounded-lg">
                    <div className="text-xl font-bold text-emerald-600 flex items-center">
                      87
                      <span className="ml-1 text-gray-400 cursor-help" title="SEO Score is calculated based on over 20 factors including meta tags, keyword density, and site structure.">❓</span>

                    </div>
                    <div className="text-sm text-gray-600">SEO Score</div>
                  </div>
                  <div className="bg-blue-50 p-4 rounded-lg">
                    <div className="text-xl font-bold text-blue-600 flex items-center">
                      1,247
                      <span className="ml-1 text-gray-400 cursor-help" title="Estimated number of keywords bringing traffic based on search visibility.">❓</span>
                    </div>
                    <div className="text-sm text-gray-600">Organic Keywords</div>
                  </div>
                </div>
                <div className="space-y-3">
                  <div className="flex text-sm items-center justify-between">
                    <span className="text-gray-600">Organic Traffic</span>
                    <span className="font-semibold text-emerald-600">+23% ↗</span>

                  </div>
                  <div className="flex text-sm items-center justify-between">
                    <span className="text-gray-600">Page Load Speed</span>
                    <span className="font-semibold text-yellow-600">2.3s</span>
                  </div>
                  <div className="flex text-sm items-center justify-between">
                    <span className="text-gray-600">Mobile Usability</span>
                    <span className="font-semibold text-emerald-600">Excellent</span>
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="technical" className="mt-6">
            <Card className="border-0 shadow-lg">
              <CardHeader>
                <CardTitle className="flex items-center">
                  <Globe className="h-5 w-5 text-indigo-600 mr-2" />
                  Technical SEO Analysis
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="flex items-center justify-between p-3 bg-emerald-50 rounded-lg">
                    <div className="flex items-center">
                      <CheckCircle className="h-5 w-5 text-emerald-500 mr-3" />
                      <span>SSL Certificate</span>
                    </div>
                    <Badge className="bg-emerald-100 text-emerald-700">Passed</Badge>
                  </div>
                  <div className="flex items-center justify-between p-3 bg-yellow-50 rounded-lg">
                    <div className="flex items-center">
                      <Clock className="h-5 w-5 text-yellow-500 mr-3 animate-pulse" />
                      <span>Page Speed</span>
                    </div>
                    <Badge className="bg-yellow-100 text-yellow-700">Needs Improvement</Badge>
                  </div>
                  <div className="flex items-center justify-between p-3 bg-emerald-50 rounded-lg">
                    <div className="flex items-center">
                      <CheckCircle className="h-5 w-5 text-emerald-500 mr-3" />
                      <span>Mobile Responsive</span>
                    </div>
                    <Badge className="bg-emerald-100 text-emerald-700">Passed</Badge>
                  </div>
                </div>
                <div className="mt-6 p-4 bg-blue-50 rounded-lg">
                  <h4 className="font-semibold text-blue-900 mb-2">AI Recommendation</h4>
                  <p className="text-blue-700 text-sm">
                    Consider optimizing image compression and enabling browser caching to improve page load speed
                    by an estimated 0.8 seconds.
                    <span className="ml-2 text-xs bg-indigo-100 text-indigo-700 px-2 py-1 rounded-full">AI-generated</span>
                  </p>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="keywords" className="mt-6">
            <Card className="border-0 shadow-lg">
              <CardHeader>
                <CardTitle className="flex items-center">
                  <TrendingUp className="h-5 w-5 text-indigo-600 mr-2" />
                  Keyword Performance
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="flex items-center justify-between p-3 border rounded-lg">
                    <div>
                      <div className="font-semibold">organic skincare products</div>
                      <div className="text-sm text-gray-600">Position 3 → 2</div>
                    </div>
                    <div className="text-right">
                      <div className="text-emerald-600 font-semibold">+1 ↗</div>
                      <div className="text-sm text-gray-600">1,200 searches/mo</div>
                    </div>
                  </div>
                  <div className="flex items-center justify-between p-3 border rounded-lg">
                    <div>
                      <div className="font-semibold">natural face cream</div>
                      <div className="text-sm text-gray-600">Position 8 → 5</div>
                    </div>
                    <div className="text-right">
                      <div className="text-emerald-600 font-semibold">+3 ↗</div>
                      <div className="text-sm text-gray-600">800 searches/mo</div>
                    </div>
                  </div>
                  <div className="flex items-center justify-between p-3 border rounded-lg">
                    <div>
                      <div className="font-semibold">eco friendly cosmetics</div>
                      <div className="text-sm text-gray-600">Position 12 → 15</div>
                    </div>
                    <div className="text-right">
                      <div className="text-red-600 font-semibold">-3 ↘</div>
                      <div className="text-sm text-gray-600">600 searches/mo</div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>

        <div className="mt-8 flex gap-4">
          <Button className="bg-indigo-600 hover:bg-indigo-700">
            <Eye className="h-4 w-4 mr-2" />
            View Full Report
          </Button>
          <Button variant="outline">
            <Download className="h-4 w-4 mr-2" />
            Download PDF
          </Button>
        </div>
      </div>


            {/* Lead Capture Form */}
            <div>
              <Card className="border-0 shadow-xl sticky top-8">
                <CardHeader>
                  <CardTitle className="text-2xl text-center">
                    {isSubmitted ? "Thank you!" : "Get your free report"}
                  </CardTitle>
                  <p className="text-gray-600 text-sm text-center">
                    {isSubmitted
                      ? "We'll send your custom report within 24 hours."
                      : "Enter your website URL and we'll generate a custom SEO report for you."}
                  </p>
                </CardHeader>
                <CardContent>
                  {!isSubmitted ? (
                    <form onSubmit={handleSubmit} className="space-y-6">
                      <div>
                        <Label htmlFor="website">Website URL</Label>
                        <Input
                          id="website"
                          type="url"
                          placeholder="https://yourwebsite.com"
                          value={website}
                          onChange={(e) => setWebsite(e.target.value)}
                          required
                          className="mt-2"
                        />
                      </div>

                      <div>
                        <Label htmlFor="email">Email Address</Label>
                        <Input
                          id="email"
                          type="email"
                          placeholder="your@email.com"
                          value={email}
                          onChange={(e) => setEmail(e.target.value)}
                          required
                          className="mt-2"
                        />
                      </div>

                      <Button type="submit" className="w-full bg-indigo-600 hover:bg-indigo-700 text-base py-3">
                        Generate My Free Report
                        <ArrowRight className="ml-2 h-5 w-5" />
                      </Button>

                      <p className="text-xs text-gray-500 text-center">
                        No spam, unsubscribe at any time. Report delivered within 24 hours.
                      </p>
                    </form>
                  ) : (
                    <div className="text-center space-y-6">
                      <div className="w-16 h-16 bg-emerald-100 rounded-full flex items-center justify-center mx-auto">
                        <CheckCircle className="h-8 w-8 text-emerald-600" />
                      </div>
                      <div>
                        <p className="text-lg font-semibold text-gray-900 mb-2">Report is being generated!</p>
                        <p className="text-gray-600">
                          We're analyzing <strong>{website}</strong> and will send your comprehensive SEO report to{" "}
                          <strong>{email}</strong> within 24 hours.
                        </p>
                      </div>
                      <Button className="w-full bg-emerald-600 hover:bg-emerald-700">
                        Start Free Trial
                        <ArrowRight className="ml-2 h-5 w-5" />
                      </Button>
                    </div>
                  )}
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </section>


      {/* Features Highlight */}
      <section className="py-10 bg-white">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-6">
            <h2 className="text-2xl lg:text-3xl font-bold text-gray-900 mb-4">What makes our reports special?</h2>
            <p className="text-base text-gray-600">AI-powered insights that go beyond basic metrics</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <Card className="border-0 shadow-md text-center">
              <CardContent className="p-6">
                <div className="w-12 h-12 bg-indigo-100 rounded-2xl flex items-center justify-center mx-auto mb-6">
                  <BarChart3 className="h-8 w-8 text-indigo-600" />
                </div>
                <h3 className="text-xl font-semibold text-gray-900 mb-4">AI-Powered Analysis</h3>
                <p className="text-gray-600 text-sm">
                  Our AI doesn't just collect data—it understands context and provides actionable insights that human
                  analysts would take hours to discover.
                </p>
              </CardContent>
            </Card>

            <Card className="border-0 shadow-md text-center">
              <CardContent className="p-6">
                <div className="w-12 h-12 bg-emerald-100 rounded-2xl flex items-center justify-center mx-auto mb-6">
                  <TrendingUp className="h-8 w-8 text-emerald-600" />
                </div>
                <h3 className="text-xl font-semibold text-gray-900 mb-4">Predictive Recommendations</h3>
                <p className="text-gray-600 text-sm">
                  Get recommendations based on industry trends and competitor analysis, not just historical data from
                  your site.
                </p>
              </CardContent>
            </Card>

            <Card className="border-0 shadow-md text-center">
              <CardContent className="p-6">
                <div className="w-12 h-12 bg-purple-100 rounded-2xl flex items-center justify-center mx-auto mb-6">
                  <Globe className="h-8 w-8 text-purple-600" />
                </div>
                <h3 className="text-xl font-semibold text-gray-900 mb-4">White-Label Ready</h3>
                <p className="text-gray-600 text-sm">
                  Every report is fully customizable with your branding, making it look like it came directly from your
                  agency.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

  {/* CTA Section */}       
         <section className="py-16 bg-indigo-600">
  <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
    <h2 className="text-2xl lg:text-3xl font-bold text-white mb-5">
      Experience AI-Powered SEO Reporting Now
    </h2>
    <p className="text-base text-indigo-100 mb-8 leading-relaxed">
      Start your free trial today and generate professional SEO reports in minutes, not hours.
    </p>

    <div className="flex flex-col sm:flex-row gap-4 justify-center">
      {/* Primary SEO-Friendly CTA */}
      <a
        href="/signup"
        className="inline-flex items-center justify-center bg-white text-indigo-600 hover:bg-gray-100 text-base px-8 py-2 font-bold rounded-lg shadow-lg hover:shadow-xl transition-all duration-300"
      >
        Start Free Trial
        <ArrowRight className="ml-2 h-5 w-5" />
      </a>

      {/* Secondary SEO-Friendly CTA */}
      <a
        href="#sample-report"
        className="inline-flex items-center justify-center bg-white/10 text-white hover:bg-white hover:text-indigo-600 text-base px-8 py-2 font-semibold rounded-lg border border-white transition-all duration-300"
      >
        See Example Report
      </a>
    </div>

    {/* Social Proof */}
    <p className="text-sm text-indigo-100 mt-6">
      No credit card required. Cancel anytime.
    </p>
  </div>
</section>


    </div>
  )
}
